### PR TITLE
Optimize ROT

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-devpack-dotnet/issues/245

### CODE REVIEW

**Comment by ShawnYun** [comment]
That looks good

**Comment by ShawnYun** [comment]
What if there is a JMP case?

**Comment by shargon** [comment]
> What if there is a JMP case?

It won't be a push, it will be a label

**Comment by ShawnYun** [comment]
For example:
```
            scriptBefore.Emit(VM.OpCode.PUSH5);
            scriptBefore.Emit(VM.OpCode.PUSH4);
            scriptBefore.EmitJump(VM.OpCode.JMP, 2);
            scriptBefore.Emit(VM.OpCode.PUSH1);
            scriptBefore.Emit(VM.OpCode.PUSH2);
            scriptBefore.Emit(VM.OpCode.PUSH3);
            scriptBefore.Emit(VM.OpCode.ROT);
```
after optimized, it will be:
```
            scriptBefore.Emit(VM.OpCode.PUSH5);
            scriptBefore.Emit(VM.OpCode.PUSH4);
            scriptBefore.EmitJump(VM.OpCode.JMP, 2);
            scriptBefore.Emit(VM.OpCode.PUSH2);
            scriptBefore.Emit(VM.OpCode.PUSH3);
            scriptBefore.Emit(VM.OpCode.PUSH1);
```
?

**Comment by shargon** [comment]
Yes because the JMP is not in the middle.

Before
image
After
image

I added a new UT with JMP,3. Please check it @ShawnYun

**Review by ShawnYun — APPROVED** [review]

**Comment by shargon** [comment]
Ready to merge?

**Pull request merged**
