### PR TITLE
skip emitting debug info for methods w/o body_Codes

### LINKED ISSUE #264: debug info generation crashes on extern methods (master-2.x)
Contracts that define static cross-contract calls via an [extern method + Appcall attribute](https://docs.neo.org/docs/en-us/sc/deploy/invoke.html#static-call) crash during debug info generation.

### PR DESCRIPTION
**Pull request by devhawk**
fixes #264 

Note, this PR also bumps version of Neo.Compiler.MSIL from 2.6 to 2.6.1. I plan on publishing the updated dotnet tool on nuget shortly after this PR is merged

### CODE REVIEW

**Comment by devhawk** [comment]
Note the failing format check doesn't appear to have anything to do with my change. workflog log reporting an encoding issue with a bunch of files that I didn't update

**Comment by lightszero** [comment]
dotnet format is not good for  text file‘s BOM

**Comment by devhawk** [comment]
thanks for fixing the formatting @lightszero !

**Comment by devhawk** [comment]
@lightszero if you let me know how you fixed my PR so it passed the format check, I'll do it myself next time

**Comment by lightszero** [comment]
you can use “notepad++” 
open a code file.
click Menu Encoding -> Convert to ANSI(this will delete some strange unvisable char and bom info)
done.

**Pull request merged**
