### PR TITLE
Create and call pointers

### PR DESCRIPTION
**Pull request by shargon**
Require https://github.com/neo-project/neo-vm/pull/317
Required for https://github.com/neo-project/neo/issues/284

Also was added a `DROP` optimization rule 

**Optimized tests require https://github.com/neo-project/neo-devpack-dotnet/pull/263**

### CODE REVIEW

**Comment by shargon** [comment]
We need to wait for #263

**Comment by shargon** [comment]
Ready to merge

**Comment by ProDog** [comment]
I have tested it.
- The callback function runs normally without arguments.
- An error occurred while compiling the contract, when the callback function has arguments:

image

In addition, an exception is thrown when deploy contract if `CreateFuncPointer()` is public:

image

**Comment by shargon** [comment]
Could you create a PR with the failing UT?

**Comment by ProDog** [comment]
> Could you create a PR with the failing UT?

I have added it https://github.com/neo-project/neo-devpack-dotnet/pull/269.

**Pull request merged**
