### PR TITLE
Add Runtime.GasLeft()

### PR DESCRIPTION
**Pull request by ProDog**
Corresponding PR https://github.com/neo-project/neo/pull/1509

### CODE REVIEW

**Comment by erikzhang** [comment]
Please fix the format.

**Comment by shargon** [comment]
Please wait for https://github.com/neo-project/neo-devpack-dotnet/pull/216

**Comment by shargon** [comment]
@ProDog Could you add some UT ?

**Comment by ProDog** [comment]
> @ProDog Could you add some UT ?

OK,I'll check after #216.

**Pull request closed without merging**
