### PR TITLE
Fix AttributeTargets of ContractHashAttribute

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Review by devhawk — COMMENTED** [review]
Why are we changing this?

**Comment by erikzhang** [comment]
Because `ContractHashAttribute` should be applied to properties. The original usage looks awkward.

**Comment by devhawk** [comment]
> Because `ContractHashAttribute` should be applied to properties. The original usage looks awkward.

Not sure it matters much if the smart contract framework declarations look awkward. But as long as this PR doesn't break compilation of existing contract source, I'm fine with it.

**Review by shargon — APPROVED** [review]
The code looks good

**Pull request merged**
