### PR TITLE
add support for switch integer

### PR DESCRIPTION
**Pull request by cloud8little**

### CODE REVIEW

**Comment by lightszero** [comment]
Have not implement that yet. I will working on it.

**Comment by Tommo-L** [comment]
plz, waiting for minutes to merge, @ShawnYun  will add some comments.

**Comment by ShawnYun** [comment]
I think we can move `CONVERT` ahead of the for loop?

**Comment by lightszero** [comment]
> I think we can move `CONVERT` ahead of the for loop?

right,that is better

**Pull request merged**
