### PR TITLE
Remove NEP17 template

### PR DESCRIPTION
**Pull request by Tommo-L**
This project will be moved to https://github.com/neo-project/examples/tree/master/csharp

### CODE REVIEW

**Comment by erikzhang** [comment]
And UT?

**Comment by shargon** [comment]
Maybe it's better to create a submodule in examples?

**Comment by Tommo-L** [comment]
> And UT?

Done

**Comment by Tommo-L** [comment]
> Maybe it's better to create a submodule in examples?

Will do it later.

**Review by erikzhang — APPROVED** [review]

**Review by vncoelho — COMMENTED** [review]
How about the other examples?
Maybe it should be a submodule there or here at least.

**Comment by erikzhang** [comment]
> How about the other examples?

Which examples?

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
The NEP-17 example should be moved as soon as possible.

**Comment by Tommo-L** [comment]
> The NEP-17 example should be moved as soon as possible.

Done, see https://github.com/neo-project/examples/pull/33

**Pull request merged**
