### PR TITLE
fix: string.Trim only trim ' '

### PR DESCRIPTION
**Pull request by nan01ab**
fix of #1186 

`string.Trim` uses same semantics with `char.IsWhiteSpace` to determine an ASCII char that is whitespace or not.

### CODE REVIEW

**Comment by nan01ab** [comment]
@Jim8y

**Comment by Jim8y** [comment]
need unit.test as well

**Review by shargon — COMMENTED** [review]
UT required

**Review by vncoelho — COMMENTED** [review]
I believe the change is correct following the logic here, but in fact a UT is necessary

**Comment by nan01ab** [comment]
UT will be added later.

**Comment by Jim8y** [comment]
> UT will be added later.

Wait, i am working on fixing the method itself, your UT will not work before that.

**Comment by Jim8y** [comment]
@shargon @vncoelho @nan01ab please check the latest update and unit test.

**Review by Jim8y — APPROVED** [review]

**Review by shargon — COMMENTED** [review]
I don't like inline methods here, but it works for you @Jim8y, I'm not against to

**Review by shargon — APPROVED** [review]

**Comment by Jim8y** [comment]
> I don't like inline methods here, but it works for you @Jim8y, I'm not against to

@shargon I know what you mean clearly, and i actually also don't like it, but doing it this way makes it eaiser to implement the method and easier to review the code.

Implement these methods purely in opcode is very hard to maintain and review. I am thinking that maybe when we have multiple these unly implementations, we can group them and make these methods into something like `suger syntax`. 

We can figure out a better way later.

**Pull request merged**
