### PR TITLE
Clean and Simplify Templates

### LINKED ISSUE #232: Clean TemplateCSharp HelloWorld
Perhaps we need to clean this folder `https://github.com/neo-project/neo-devpack-dotnet/tree/master/templates/Template.CSharp`

It looks like we just need two files:

* `Contract1.cs`
* `ProjectTemplate.csproj`

### PR DESCRIPTION
**Pull request by vncoelho**
closes #232 #231 

TODO #231 : Simplify the folder path or change it to a variable that can be setup easily on different OS and docker files.

### CODE REVIEW

**Comment by erikzhang** [comment]
Can you explain the purpose of these changes? Because I see most changes are unnecessary or wrong.

**Comment by belane** [comment]
@vncoelho sorry I don't understand, why remove projects?

**Comment by vncoelho** [comment]
I think that there are old files on the basic Hello World template, such as `Template.CSharp.csproj`.
We need a clean simple `Hello World`.

The other change is related to the `\` @belane.
On several OS we need paths related using `/`.
Then, the idea is to change the variable you are using `$SolutionDir` to another one easier to configure.

Did you have check the issues? @belane and @erikzhang ?

**Comment by vncoelho** [comment]
I closed the issues and PR because I am not used to CSharp configurations, thus, perhaps, are you are saying these changes are not necessary.

Locally here we can do a workaround for fixing the paths of the `PostBuild`.

**Pull request closed without merging**
