### PR TITLE
Export enum types

### LINKED ISSUE #464: enum type of SmartContractFramework can not be recognized
Oracle contract:  https://github.com/neo-project/examples/blob/6f63197932674a6e29cdb7598a8cabee88e56784/csharp/Oracle/OracleDemo.cs#L23

```cs
public static void Callback(string url, string userdata, OracleResponseCode code, string result)
        {
            if (code != OracleResponseCode.Success) throw new Exception("Oracle response failure with code " + (byte)code);

            object ret = Json.Deserialize(result); // [ "hello world" ]
            object[] arr = (object[])ret;
            string value = (string)arr[0];

            Runtime.Log("userdata: " + userdata);
            Runtime.Log("response value: " + value);
        }
```

Build the contract using the latest neo core and the compiler. Build nef and manifest file successfully. but it shows type unknown in the manifest file.

`{"name":"code","type":"Unknown:Neo.SmartContract.Framework.Services.Neo.OracleResponseCode"}`

### PR DESCRIPTION
**Pull request by erikzhang**
Close #464

### CODE REVIEW

**Comment by erikzhang** [comment]
@cloud8little Can you test it?

**Comment by cloud8little** [comment]
> @cloud8little Can you test it?

it does not work, the type is still unknown.

**Comment by erikzhang** [comment]
It works on mine.

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
@cloud8little can you test it again?

**Comment by cloud8little** [comment]
> @cloud8little can you test it again?

yes, passed.

**Review by cloud8little — APPROVED** [review]

**Pull request merged**
