### PR TITLE
Fix HelloWorld

### PR DESCRIPTION
**Pull request by Tommo-L**
Close https://github.com/neo-project/neo-devpack-dotnet/issues/454

@vncoelho  Could you try it?

### CODE REVIEW

**Review by vncoelho — COMMENTED** [review]
```cs

/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Contract1.cs(27,20): error CS0266: Cannot implicitly convert type 'Neo.SmartContract.Framework.ByteString' to 'byte[]'. An explicit conversion exists (are you missing a cast?) [/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj]
```

**Review by erikzhang — APPROVED** [review]

**Review by vncoelho — COMMENTED** [review]
Still with conversion error, @Tommo-L .
```cs
/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Contract1.cs(27,20): error CS0266: Cannot implicitly convert type 'Neo.SmartContract.Framework.ByteString' to 'byte[]'. An explicit conversion exists (are you missing a cast?) [/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj]
```

**Comment by erikzhang** [comment]
@Tommo-L `string` can be converted to `ByteString` implicitly.

https://github.com/neo-project/neo-devpack-dotnet/blob/4902638e16f2cfa9df0e75776b3f83b4197a3601/src/Neo.SmartContract.Framework/ByteString.cs#L23

**Comment by erikzhang** [comment]
@vncoelho Are you using preview5? I think it should work.

**Comment by Tommo-L** [comment]
Nep17 works with string.

**Comment by Tommo-L** [comment]
> Still with conversion error, @Tommo-L .
> 
> ```cs
> /neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Contract1.cs(27,20): error CS0266: Cannot implicitly convert type 'Neo.SmartContract.Framework.ByteString' to 'byte[]'. An explicit conversion exists (are you missing a cast?) [/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj]
> ```

Fixed

**Comment by Tommo-L** [comment]
Demo passed
image

**Review by erikzhang — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Review by vncoelho — APPROVED** [review]
Fixed and working on `Preview5`
Go to https://neocompiler.io/#nav-compilers/, click on Compile.

After compilation go to https://neocompiler.io/#nav-native/

image

**Pull request merged**
