### PR TITLE
add notify manner to assert

### PR DESCRIPTION
**Pull request by Liaojinghui**
Allow developers to send notification on faulty assert

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
I think that maybe we should use notify always, or create a new method instead of an argument, with the same behavior, Assert(false) instead of Abort

**Comment by Liaojinghui** [comment]
> I think that maybe we should use notify always, or create a new method instead of an argument, with the same behavior, Assert(false) instead of Abort

@erikzhang any suggestion?

**Comment by erikzhang** [comment]
I think `Log` is more reasonable than `Notify`.

**Comment by Liaojinghui** [comment]
> I think `Log` is more reasonable than `Notify`.

@erikzhang so I just keep this pr and allow developers to choose? This pr won't change any existing contract anyway. Can we merge?

**Comment by Liaojinghui** [comment]
> Maybe it's better to add a compilation option in order to choose the type

Any particular reason makes a compilation option better than a default parameter?

**Comment by shargon** [comment]
> @shargon Any particular reason makes a compilation option better than a default parameter?

Gas saving, default parameter require to push the stack item

**Comment by Liaojinghui** [comment]
> Gas saving, default parameter require to push the stack item

got that, may you do an option pr?

**Pull request closed without merging**
