### PR TITLE
Created Inline attribute to mix OpCode/Syscalls/etc

### PR DESCRIPTION
**Pull request by igormcoelho**
See: https://github.com/neo-project/neo-compiler/pull/142

### CODE REVIEW

**Comment by igormcoelho** [comment]
Example:
```cs
Storage.Put("Hello", "World");
```
generates:
```
01 PUSHBYTES1 61 # a
01 PUSHBYTES1 62 # b
61 NOP  # Does nothing.
7c SWAP  # The top two items on the stack are swapped.
68 SYSCALL 164e656f2e53746f726167652e476574436f6e74657874 # Neo.Storage.GetContext
68 SYSCALL 0f4e656f2e53746f726167652e507574 # Neo.Storage.Put
```

But it can be used with other opcodes too:
```cs
        [Inline(OpCode.SYSCALL, "Neo.Blockchain.GetHeight")]
        [Inline(OpCode.INC)]
        public extern static int HeightPlus1();
```
Generates:
```
68 SYSCALL 184e656f2e426c6f636b636861696e2e476574486569676874 # Neo.Blockchain.GetHeight
8b INC  # 1 is added to the input.
```

We cannot mix Inline attribute with others... example (fails):
```cs
        [Inline(OpCode.SYSCALL, "Neo.Blockchain.GetHeight")]
        [OpCode(OpCode.INC)]
        public extern static int HeightPlus1();
```
or: 
```cs
        [Syscall("Neo.Blockchain.GetHeight")]
        [Inline(OpCode.INC)]
        public extern static int HeightPlus1();
```

It's working for SYSCALL (including parameters) and OpCode (without parameters)... but it could be extended in the future to any OpCode, including APPCALLS, etc. But for now it's enough, I hope :)

**Comment by erikzhang** [comment]
I think you can just change the `OpCodeAttribute` and `SyscallAttribute` to `AllowMultiple = true` without adding `InlineAttribute`.

**Comment by igormcoelho** [comment]
I have to agree, the idea is nice. must how to handle these orders :)

**Comment by igormcoelho** [comment]
Will rethink this.

**Pull request closed without merging**
