### PR TITLE
ensure correct order

### PR DESCRIPTION
**Pull request by Jim8y**
this pr ensures that the coverage is calculated after the artifacts is updated.

### CODE REVIEW

**Comment by Jim8y** [comment]
The github action often fails because of coverage null. thus having this pr that ensures coverage is calculated after the compilation.

**Comment by Jim8y** [comment]
action was executed multiple times, it works.

**Review by shargon — COMMENTED** [review]
like this is always checked that the artifacts are the same, previously is like a unit test, you can skip that part

**Comment by shargon** [comment]
I understand the problem, if you choose one UT, is not selected the cleanUp

**Comment by shargon** [comment]
@Jim8y you prefer to work on this one or in #1109, because it's almost the same

**Comment by Jim8y** [comment]
> @Jim8y you prefer to work on this one or in #1109, because it's almost the same, (I need this code to fix the compilation of unique unit test)

just finish yours, mine can wait here to see if your work fulfill my need. But this pr mainly focus on solve the github action fail issue, not sure if your pr can do the same.

**Comment by Jim8y** [comment]
With https://github.com/neo-project/neo-devpack-dotnet/pull/1109 this pr is no longer needed.

**Pull request closed without merging**
