### PR TITLE
Check dotnet format in travis

### PR DESCRIPTION
**Pull request by shargon**
This will prevent to push any format error

Related to https://github.com/neo-project/neo/issues/982

### CODE REVIEW

**Comment by shargon** [comment]
Works as expected

**Comment by shargon** [comment]
@igormcoelho it seems that CRLF is checked here, isn't it?

**Comment by igormcoelho** [comment]
Let's format this before 93... it's too complicated to review. This code was never properly indented :joy:

**Comment by igormcoelho** [comment]
@shargon can you reopen this in your branch? I cannot write over neo directly, I don't know why...

**Comment by igormcoelho** [comment]
Ok, I created another repo clone with write access here. Let's fix travis before 94, so changes will be much easier to track (compiler is tricky).

**Comment by igormcoelho** [comment]
Man, this code is so non-formatted... I don't know what to do here. Let's just pass these basic changes for now... and we format it in time perhaps...

**Comment by shargon** [comment]
> If tests pass, we should merge this ASAP (24hrs and counting).

image

**Comment by shargon** [comment]
We should unify **in a future** the name of the folders across all the projects

**Comment by igormcoelho** [comment]
Yes.. in fact this one I like more: `src` and `tests`. Just a typo causing headache here :joy:

**Comment by shargon** [comment]
PASSED!

**Comment by igormcoelho** [comment]
double-check is always good precaution :+1:
:joy:

**Comment by igormcoelho** [comment]
Sorry guys, we need to review 93. This is blocking us.

**Pull request merged**
