### PR TITLE
Split MethodConvert.cs file

### PR DESCRIPTION
**Pull request by chenzhitong**
close https://github.com/neo-project/neo-devpack-dotnet/issues/848

### CODE REVIEW

**Comment by chenzhitong** [comment]
> > close #848
> 
> #848 is composed of 5 pr, one is done, this close the 4 others ones?

Yes, but waiting for LiaoJinghui to review, maybe it needs more modifications and added comments

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
Compared methods by methods, no code change.

**Comment by Jim8y** [comment]
@shargon please check. After this one is merged. Please keep working on adding comments and examples. Would be great if we can directly generate documents from comments. As detail as possible.

**Comment by Jim8y** [comment]
> > > close #848
> > 
> > 
> > #848 is composed of 5 pr, one is done, this close the 4 others ones?
> 
> Yes, but waiting for Jim8y to review, maybe it needs more modifications and added comments

One pr on one thing. Comments in another pr.

**Review by shargon — COMMENTED** [review]
~@chenzhitong could you give write rights?~ (I think I have)

**Review by shargon — APPROVED** [review]

**Pull request merged**
