### PR TITLE
Revert "publish neon to myget/github packages"

### PR DESCRIPTION
**Pull request by shargon**
Related to https://github.com/neo-project/neo-devpack-dotnet/pull/393

### CODE REVIEW

**Comment by erikzhang** [comment]
@devhawk The package of neon is too large. Maybe we can publish the library only (not include the dotnet tools).

**Comment by devhawk** [comment]
> @devhawk The package of neon is too large. Maybe we can publish the library only (not include the dotnet tools).

The tool is the part that matters. I'm not sure what projects use the library directly.

Based on my local testing, `--include-source` is creating an additional 18mb symbols package. Is that getting uploaded to myget? I don't think we need to tool package to include symbols and source

**Comment by shargon** [comment]
Shall I remove `--include-source` first?

**Comment by erikzhang** [comment]
> --include-source is creating an additional 18mb symbols package.

Even without the symbols package, the nupkg file itself is 18MB in size. MyGet only has 100MB of space.

**Comment by devhawk** [comment]
> MyGet only has 100MB of space.

Could we publish at least the neon tool somewhere other than myget? Azure artifacts free tier is 2gb and it's only $2 USD / month / GB above that. Or we could use [sleet](https://github.com/emgarten/Sleet) to publish a feed on AWS or Azure storage - that would be under a $1 USD / month

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
