### PR TITLE
Fix struct initialization

### PR DESCRIPTION
**Pull request by shargon**
Test for https://github.com/neo-project/neo-devpack-dotnet/issues/168

### CODE REVIEW

**Comment by shargon** [comment]
@lightszero Could you take a look? it fails in `setItem`

```
op:[0000]INITSLOT
op:[0003]PUSH1
op:[0004]NEWARRAY
op:[0005]DUP
op:[0006]PUSH0
op:[0007]PICKITEM
op:[0008]STLOC0
op:[0009]LDLOC0
op:[000A]LDARG0
op:[000B]PUSH0
op:[000C]SWAP
op:[000D]SETITEM
```

**Comment by shargon** [comment]
I think that the problem is that it using a ref value.

**Comment by lightszero** [comment]
@shargon checked ,this is not about #168
if you use "class State" it will be fine.
but “struct State" will be crash.

becauce Array in NeoVM is  more like object[]
a struct[] do not need to initialization,it is just a  memory block,c# just fill allbytes to zero.

we do not have a samething like struct[] yet.

**Review by lightszero — CHANGES_REQUESTED** [review]
use class State will be fine.

**Comment by Qiao-Jin** [comment]
I have once post a draft PR #379 whose logic might help for struct initialization (though at first I think this is to solve some problems for class initialization before I realize that class object can be initialized via code in main function).

**Pull request closed without merging**
