### PR TITLE
[NEP4] Adding support for Dynamic Contract Invokes

### PR DESCRIPTION
**Pull request by localhuman**
In regards to this NEP https://github.com/neo-project/proposals/pull/19

Adding method `DynamicAppCall` to Neo.SmartContract.Framework.SmartContract for dynamic app call invokes.

### CODE REVIEW

**Comment by localhuman** [comment]
Recent change set uses `System.Func` instead.  A proposed usage of this approach is here:

https://github.com/localhuman/examples-csharp/blob/feature-dynamic-invoke/RuntimeInvoke/RuntimeInvoke.cs

**Comment by erikzhang** [comment]
We can make it easier:
```c#
public static void Main(Func<int, int, int> add)
{
    add(1, 2);
}
```

**Comment by erikzhang** [comment]
@lightszero Can we change the compiler to support this?

**Comment by lightszero** [comment]
yes,working on it.

**Pull request closed without merging**
