### PR TITLE
Add Nep17Token base class

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by ProDog** [comment]
In order to avoid the https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108, I added `new` keyword, but the results of the compilation do not change. 
```C#
        public static new void Mint(UInt160 to, BigInteger amt)
        {
            Mint(to, amt);
        }

        public static new void Burn(UInt160 account, BigInteger amt)
        {
            Burn(account, amt);
        }
```
The contract will report an error:
```
VM State: FAULT
Gas Consumed: 0.1885788
Result Stack: []
Error: MaxStackSize exceed: 2049
```

**Comment by erikzhang** [comment]
Your contract is executing a recursive call and there is no exit. I think you want to call the `Mint` and `Burn` methods of the base class. Then you must use the class name.

```c#
public static new void Mint(UInt160 to, BigInteger amt)
{
    Nep17Token.Mint(to, amt);
}

public static new void Burn(UInt160 account, BigInteger amt)
{
    Nep17Token.Burn(account, amt);
}
```

**Comment by ProDog** [comment]
Yes, it's worked use the class name.

**Comment by ProDog** [comment]
Tested OK.

**Comment by erikzhang** [comment]
Merge?

**Comment by ProDog** [comment]
Merge!

**Pull request merged**
