### PR TITLE
Allow Multiple return

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-debugger/issues/17

### CODE REVIEW

**Comment by shargon** [comment]
@lightszero could you check my code, when we return directly the multiple values it works, but the problem is if we use before this ValueTuple, it still use `PICKITEM`.

**Comment by lightszero** [comment]
ValueTuple is new for me，I will study that.

**Comment by lightszero** [comment]
@shargon had fixed

**Comment by ProDog** [comment]
`returnType` is incorrect.

contract:
```
public static (int, int) Return(int a, int b)
 {
            return (a / b, a % b);
 }
```

amnifest.json:
```
 {
            "name":"return",
            "parameters":
            [
                {
                    "name":"a",
                    "type":"Integer"
                },
                {
                    "name":"b",
                    "type":"Integer"
                }
            ],
            "returnType":"Unknown:System.ValueTuple`2<System.Int32,System.Int32>"
        }
```

We need other modifications @lightszero

**Comment by lightszero** [comment]
We can make another issue and pr for it. 
what is returnType should be?
@ProDog

**Comment by ProDog** [comment]
For multiple return, the  `returnType`  is more than one, I think like this:
```
 {
            "name":"return",
            "parameters":
            [
                {
                    "name":"a",
                    "type":"Integer"
                },
                {
                    "name":"b",
                    "type":"Integer"
                }
            ],            
            "returnType":["Integer","Integer"]
}
```

**Comment by lightszero** [comment]
> For multiple return, the `returnType` is more than one, I think like this:
> 
> ```
>  {
>             "name":"return",
>             "parameters":
>             [
>                 {
>                     "name":"a",
>                     "type":"Integer"
>                 },
>                 {
>                     "name":"b",
>                     "type":"Integer"
>                 }
>             ],            
>             "returnType":["Integer","Integer"]
> }
> ```

that is a option,please create a new issue for it.

**Comment by erikzhang** [comment]
It should be `Struct`.

**Comment by erikzhang** [comment]
We shouldn't support multiple return in public methods.

**Pull request merged**
