### PR TITLE
fix ConvertStArg

### LINKED ISSUE #419: Slot initialized error when change local variables in contract and return type is void
contract like this(change a's value and put the value back to a ):

```cs
        public static void Testvoid(int a, int b)
        {
            a = a + 2;
        }
```

```
optimization ratio = 71.296295%
op:[0045]INITSLOT
op:[0048]LDARG0
op:[0049]PUSH2
op:[004A]ADD
op:[004B]STLOC0
System.InvalidOperationException: Slot has not been initialized.
   at Neo.VM.ExecutionEngine.ExecuteStoreToSlot(Slot slot, Int32 index) in D:\Github\neo-vm\src\neo-vm\ExecutionEngine.cs:line 1309
   at Neo.VM.ExecutionEngine.ExecuteInstruction() in D:\Github\neo-vm\src\neo-vm\ExecutionEngine.cs:line 566
   at Neo.VM.ExecutionEngine.ExecuteNext() in D:\Github\neo-vm\src\neo-vm\ExecutionEngine.cs:line 1294
```

or 

```cs
        public static void testvoidinputstring(string a)
        {
            a = a + "abc";
        }
```

### PR DESCRIPTION
**Pull request by Qiao-Jin**
Close #419

### CODE REVIEW

**Review by erikzhang — APPROVED** [review]

**Comment by cloud8little** [comment]
Test with these contracts, both passed.

```cs
        public static int Testvoid(int a, int b)
        {
            a = a + 2;
            return a + b;
        }
```

```cs
        public static void Testvoid(int a, int b)
        {
            a = a + 2;
        }
```

**Comment by cloud8little** [comment]
@Qiao-Jin  can you help add the test contract as UT?

**Comment by Qiao-Jin** [comment]
> @Qiao-Jin can you help add the test contract as UT?

Have added

**Review by erikzhang — APPROVED** [review]

**Review by vncoelho — APPROVED** [review]

**Review by cloud8little — APPROVED** [review]

**Review by shargon — COMMENTED** [review]
Good!

**Pull request merged**
