### PR TITLE
Fixed some known issues

### PR DESCRIPTION
**Pull request by chenzhitong**
Fixed bug: Plugin is not compatible with VS2019; https://github.com/neo-project/neo-devpack-dotnet/issues/43
Fixed bug: Can not load NuGet package;

### CODE REVIEW

**Comment by chenzhitong** [comment]
@steven1227

**Comment by erikzhang** [comment]
We should use NuGet in templates.

**Comment by erikzhang** [comment]
@chenzhitong This should solve the nuget problem: c667d35c975d7d06d9957f7690f0c724dfc21a8f

**Comment by chenzhitong** [comment]
https://github.com/neo-project/neo-devpack-dotnet/commit/c667d35c975d7d06d9957f7690f0c724dfc21a8f This commit run error:  @erikzhang 

Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Neo.SmartContract.Framework, Version=2.9.3.0, Culture=neutral, PublicKeyToken=null'


image

**Comment by erikzhang** [comment]
Wait for #47 and I will test it again.

**Comment by vncoelho** [comment]
@chenzhitong, maybe you can resolve the conflicts or open another new PR.

**Pull request closed without merging**
