### PR TITLE
New Methods: add string methods to make it easier to process string

### PR DESCRIPTION
**Pull request by Jim8y**
This pr adds some string methods that can be used in smart contract:

`Replace`
`Take`
`Last`
`Reverse`

Checklist of string methods:

- [ ] String.Compare(string, string)
- [ ] String.Compare(string, string, bool)
- [ ] String.Compare(string, int, string, int, int)
- [ ] String.Compare(string, int, string, int, int, bool)
- [ ] String.CompareOrdinal(string, string)
- [ ] String.CompareOrdinal(string, int, string, int, int)
- [ ] String.Concat(params string[])
- [ ] String.Concat(IEnumerable<string>)
- [ ] String.Concat(object)
- [ ] String.Concat(object, object)
- [ ] String.Concat(object, object, object)
- [ ] String.Concat(params object[])
- [ ] String.Contains(string)
- [ ] String.Contains(string, StringComparison)
- [ ] String.Copy(string)
- [ ] String.EndsWith(string)
- [ ] String.EndsWith(string, StringComparison)
- [ ] String.Equals(string)
- [ ] String.Equals(string, string)
- [ ] String.Equals(string, string, StringComparison)
- [ ] String.Format(string, object)
- [ ] String.Format(string, object, object)
- [ ] String.Format(string, object, object, object)
- [ ] String.Format(string, params object[])
- [ ] String.Format(IFormatProvider, string, params object[])
- [ ] String.GetHashCode()
- [ ] String.IndexOf(char)
- [ ] String.IndexOf(char, int)
- [ ] String.IndexOf(char, int, int)
- [ ] String.IndexOf(string)
- [ ] String.IndexOf(string, int)
- [ ] String.IndexOf(string, StringComparison)
- [ ] String.IndexOf(string, int, int)
- [ ] String.IndexOf(string, int, StringComparison)
- [ ] String.IndexOf(string, int, int, StringComparison)
- [ ] String.IndexOfAny(char[])
- [ ] String.IndexOfAny(char[], int)
- [ ] String.IndexOfAny(char[], int, int)
- [ ] String.Insert(int, string)
- [ ] String.Intern(string)
- [ ] String.IsInterned(string)
- [ ] String.IsNullOrEmpty(string)
- [ ] String.IsNullOrWhiteSpace(string)
- [ ] String.Join(string, IEnumerable<string>)
- [ ] String.Join(string, params string[])
- [ ] String.Join(string, string[], int, int)
- [ ] String.Join<T>(string, IEnumerable<T>)
- [ ] String.LastIndexOf(char)
- [ ] String.LastIndexOf(char, int)
- [ ] String.LastIndexOf(char, int, int)
- [ ] String.LastIndexOf(string)
- [ ] String.LastIndexOf(string, int)
- [ ] String.LastIndexOf(string, StringComparison)
- [ ] String.LastIndexOf(string, int, int)
- [ ] String.LastIndexOf(string, int, int, StringComparison)
- [ ] String.LastIndexOfAny(char[])
- [ ] String.LastIndexOfAny(char[], int)
- [ ] String.LastIndexOfAny(char[], int, int)
- [ ] String.Normalize()
- [ ] String.Normalize(NormalizationForm)
- [ ] String.PadLeft(int)
- [ ] String.PadLeft(int, char)
- [ ] String.PadRight(int)
- [ ] String.PadRight(int, char)
- [ ] String.Remove(int)
- [ ] String.Remove(int, int)
- [ ] String.Replace(char, char)
- [ ] String.Replace(string, string)
- [ ] String.Split(char[], StringSplitOptions)
- [ ] String.Split(char[], int, StringSplitOptions)
- [ ] String.Split(string[], StringSplitOptions)
- [ ] String.Split(string[], int, StringSplitOptions)
- [ ] String.StartsWith(string)
- [ ] String.StartsWith(string, StringComparison)
- [ ] String.Substring(int)
- [ ] String.Substring(int, int)
- [ ] String.ToLower()
- [ ] String.ToLower(CultureInfo)
- [ ] String.ToLowerInvariant()
- [ ] String.ToUpper()
- [ ] String.ToUpper(CultureInfo)
- [ ] String.ToUpperInvariant()
- [ ] String.Trim()
- [ ] String.Trim(char[])
- [ ] String.TrimEnd()
- [ ] String.TrimEnd(char[])
- [ ] String.TrimStart()
- [ ] String.TrimStart(char[])

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
Why bot use native .Substring and  .Replace?

**Comment by shargon** [comment]
> > Why not use native .Substring and  .Replace?
> 
> a simple answer to this is when we use string, we use is as we use in c#, when we check if its supported, we try to find how to implememt it in place that looks like where we can find it. these methods only make it easier to use neo, wont cause any trouble.

I think that we should ensure that the native methods works instead of create new ones

**Comment by Liaojinghui** [comment]
> I think that we should ensure that the native methods works instead of create new ones

I am sorry, i dont understand, do we have a native method callded Replace for string? And substring is native for sure cause i did not create another substring here.

**Comment by Liaojinghui** [comment]
> string.Replace

@shargon no we dont have it.

**Comment by shargon** [comment]
> > string.Replace
> 
> @shargon no we dont have it.

That's I said, I prefer to fix support the native methods instead of create a new ones.

**Comment by Liaojinghui** [comment]
are you saying you prefer maintain the status quo?

**Comment by shargon** [comment]
> are you saying you prefer maintain the status quo?

I think that we can do "mystr".Replace("str","") without creating a new Helper methods, modifying the compiler

**Comment by Jim8y** [comment]
> > are you saying you prefer maintain the status quo?
> 
> I think that we can do "mystr".Replace("str","") without creating a new Helper methods or extensions, just modifying the compiler

Whats the benefits of doing it that way? I would say it will be very very long `AddInstruction` commands.

**Comment by cschuchardt88** [comment]
If you make substring native you should use `"str".AsSpan(Start, Length)`. Much faster than substring.

**Comment by Jim8y** [comment]
> If you make substring native you should use `"str".AsSpan(Start, Length)`. Much faster than substring.

`replacce a substring` i mean use `Replace` to replace a substring of a string...... not replace the substring.

And I neo, we execute Opcode, so  AsSpan will not make anything faster.

**Comment by shargon** [comment]
> Whats the benefits of doing it that way?

c# developers will prefer to use `"".Replace`, instead of a new "library", "helper" or "extension"

**Comment by Jim8y** [comment]
> > Whats the benefits of doing it that way?
> 
> c# developers will prefer to use `"".Replace`, instead of a new "library", "helper" or "extension"

Its exactly `"".Replace` as you said.

**Comment by cschuchardt88** [comment]
Can we organize the Helper classes? Split them up into their only type helper class. For Example `Neo.StringHelper`, `Neo.IntegerHelper`, `Neo.ArrayHelper`, `Neo.CharHelper`. It will help for later when we remove `dotnet` native functionally and switch to `Neo` native.

**Comment by shargon** [comment]
> > > Whats the benefits of doing it that way?
> > 
> > 
> > c# developers will prefer to use `"".Replace`, instead of a new "library", "helper" or "extension"
> 
> Its exactly `"".Replace` as you said.

But Is not the system extension, require a different using

**Comment by Jim8y** [comment]
> But Is not the system extension, require a different using

So?

**Comment by shargon** [comment]
I mean, we should allow this methods in the compiler, not require an extra extension, if the developer use, `char.IsAsciiLetter(c)` it should work

**Comment by cschuchardt88** [comment]
> > > > Whats the benefits of doing it that way?
> > > 
> > > 
> > > c# developers will prefer to use `"".Replace`, instead of a new "library", "helper" or "extension"
> > 
> > 
> > Its exactly `"".Replace` as you said.
> 
> But Is not the system extension, require a different using

Not if you have the same `namespace`.

**Pull request closed without merging**
