### PR TITLE
delete codes after finally when finally throws or aborts

### PR DESCRIPTION
**Pull request by Hecate2**

### CODE REVIEW

**Comment by Hecate2** [comment]
There is still bug. `throwed` should be associated with FINALLY stack, in order to judge if the code had throwed in try/catch corresponding to the finally.

**Comment by shargon** [comment]
> There is still bug. `throwed` should be associated with FINALLY stack, in order to judge if the code had throwed in try/catch corresponding to the finally. Otherwise we cannot judge the meaning of `throwed` in finally.

Could you open a issue for it?

**Comment by Hecate2** [comment]
> > There is still bug. `throwed` should be associated with FINALLY stack, in order to judge if the code had throwed in try/catch corresponding to the finally. Otherwise we cannot judge the meaning of `throwed` in finally.
> 
> Could you open a issue for it?

Already fixed in the latest commit c0a0eefc4ba929384c87385d76659a4ccfd7b8c5

**Comment by Hecate2** [comment]
ABORT in finally is not handled well

**Review by Jim8y — APPROVED** [review]

**Review by shargon — COMMENTED** [review]
LGTM

**Pull request merged**
