### PR TITLE
Support ArrayInitializerExpression

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by shargon** [comment]
I will add some UT

**Comment by erikzhang** [comment]
@shargon Are you still working on this?

**Comment by shargon** [comment]
It fault during with `ImplicitArrayCreationExpressionSyntax`. I upload the UT

image

**Comment by erikzhang** [comment]
@shargon Fixed!

**Review by shargon — APPROVED** [review]

**Pull request merged**
