### PR TITLE
Generate default manifest file when compiling

### LINKED ISSUE #91: Neon compiler isn't ready for NEO3 contract deployment
Find many issues need to be fixed in neon complier since it doesn't sync to the latest  neo3 vm.
It's necessary for deploying contract on neo3.
image

### PR DESCRIPTION
**Pull request by shargon**
Close #91

Fix ABI issues

@superboyiii This is the expected value for neo-cli

### CODE REVIEW

**Comment by superboyiii** [comment]
> Close #91
> 
> @superboyiii This is the expected value for neo-cli

Wow, great, Let me test it.

**Comment by shargon** [comment]
@superboyiii Please, could you try again?

**Comment by superboyiii** [comment]
> @superboyiii Please, could you try again?

Success! But there seems still something wrong on sc execution.
image
image

**Comment by shargon** [comment]
Try without `if (Runtime.Trigger == TriggerType.Application)`

**Comment by lock9** [comment]
I decompiled the script deployed and it doesn't look healthy:
image

Shouldn't it have a "PUSHDATA2" or equivalent? My code can be broken, but I checked it manually and it seems that there is something wrong in the serialization of the smart contract

**Comment by shargon** [comment]
I will review it

**Comment by shargon** [comment]
@lock9 This is the deploy or the smartcontract? The deploy script looks good in my test, and the contract was created

**Comment by shargon** [comment]
The smart contract looks good too
image

I will review it with a real deploy

**Comment by superboyiii** [comment]
> The smart contract looks good too
> image
> 
> I will review it with a real deploy

Yes, you're right. If I remove the Runtime.Trigger, it works well.
image

**Comment by shargon** [comment]
Without remove the Trigger it works to me, is the same code you provide me

image

image

**Comment by shargon** [comment]
@superboyiii You are trying with RPC, could you test it by neo-cli?

**Comment by superboyiii** [comment]
> @superboyiii You are trying with RPC, could you test it by neo-cli?

Add the Trigger and invoke it inside neo-cli, still return "".
image
I'm using SmartContract.Framework 2.9.3.1, is it related to this issue?

**Comment by shargon** [comment]
Please, send me your nef and manifest file
This is mine.
[sc.zip](https://github.com/neo-project/neo-devpack-dotnet/files/3625996/sc.zip)

**Comment by superboyiii** [comment]
Yours works well on mine. But I'm not sure which course is different between us. Here's mine.
[owen.zip](https://github.com/neo-project/neo-devpack-dotnet/files/3626418/owen.zip)

**Comment by shargon** [comment]
@superboyiii  Could you add your source? looks different as the first version

image

**Comment by shargon** [comment]
> I'm using SmartContract.Framework 2.9.3.1, is it related to this issue?

I used the library inside the repository, not the nuget

**Comment by superboyiii** [comment]
Oh, Maybe that's the point. I use the nuget, maybe it's incompatible.

**Comment by superboyiii** [comment]
Oh, Maybe that's the point. I use the nuget, maybe it's incompatible.

**Comment by superboyiii** [comment]
Oh, Maybe that's the point. I use the nuget, maybe it's incompatible.

**Comment by shargon** [comment]
@superboyiii this is the issue

The new version use this syscall 

https://github.com/neo-project/neo-devpack-dotnet/blob/f461e54b5e4cdf9dec0c8cc32652e01edd0add70/src/Neo.SmartContract.Framework/Services/Neo/Runtime.cs#L7

And the nuget version use this

https://github.com/neo-project/neo-devpack-dotnet/blob/5edcebe28928c7e2a2b6065d8fed8abc76192192/Neo.SmartContract.Framework/Services/Neo/Runtime.cs#L7

So you need to use the library from the bin folder, until we release a nuget for 3x (wait for https://github.com/neo-project/neo-devpack-dotnet/pull/106)

**Comment by superboyiii** [comment]
All right.  Let me try it again.

**Comment by shargon** [comment]
Also I added here https://github.com/neo-project/neo-cli/pull/463/commits/2360e7a3302f8782dfb4c3c4542c6b0202aa6b10 some checks in order to prevent this issues in the future.

**Comment by superboyiii** [comment]
> Also I added here [neo-project/neo-cli@2360e7a](https://github.com/neo-project/neo-cli/commit/2360e7a3302f8782dfb4c3c4542c6b0202aa6b10) some checks in order to prevent this issues in the future.

Good job! Thanks for your suggestion, mine works well now.

**Comment by shargon** [comment]
Thanks you!

**Comment by shargon** [comment]
Ping @lightszero

**Pull request merged**
