### PR TITLE
Fix Parser-DeleteDeadCode

### LINKED ISSUE #246: Modify optimizer of `Parser_DeleteDeadCode`
Now if we use abi offset, we will remove the automain method. The  optimizer  can't  find all method entry points. So we will modify it later.

### PR DESCRIPTION
**Pull request by ShawnYun**
close #246

### CODE REVIEW

**Comment by shargon** [comment]
Could you add some ut for `DELETE_DEAD_CODE`?

**Comment by ShawnYun** [comment]
Yes, I will add UT for it.

**Comment by lightszero** [comment]
give me some time,I think need to check this code carefully.

**Comment by lightszero** [comment]
I had checked this code.and I do not think this is a good idea.

we need to split INefItem[]  to several groups by methods.
parse singe group is safe,and do not need to change any code in parser.
and finally,just link back.

**Comment by lightszero** [comment]
@ShawnYun  I made a framework for this
https://github.com/neo-project/neo-devpack-dotnet/pull/263/checks?check_run_id=638155201
we should close this pr and working on that.
can you add unittest for that?

**Pull request closed without merging**
