### PR TITLE
Renaming AVM to NVM

### PR DESCRIPTION
**Pull request by vncoelho**
closes https://github.com/neo-project/neo-compiler/issues/149

### CODE REVIEW

**Comment by shargon** [comment]
We should configure travis in this project before

**Comment by vncoelho** [comment]
Perfect, @shargon! Let's do it!

**Comment by erikzhang** [comment]
Maybe we should change the suffix name to `.bin`?

**Comment by shargon** [comment]
both are good for me

**Comment by igormcoelho** [comment]
@erikzhang it's important to enforce a clear extension format.
being it `.avm` or `.nvm`, we write extensions to editors like VSCode that automatically parse binary format into neovm opcodes. I think that `.bin` is usually reserved for native computing architectures like x86-64... Unless you are also planning to create a hardware specially for it xD

**Comment by vncoelho** [comment]
Travis is on, can we merge this and https://github.com/neo-project/neo-cli/pull/381?

**Comment by lightszero** [comment]
.avm = Antshares's VM 's bytecode file format, 

but no language use the VM as output file's ext name;
Java->build target->.jar  not .jvm
C#->build target->.dll not .il


how about use double ext name

.contract.bin  

.bin mean is file is binary
.contract mean is a contract

**Comment by lightszero** [comment]
btw

 jar = Java Archive
dll = Dynamic Link Library

**Comment by vncoelho** [comment]
As you want, but I still prefer NVM, because we have a limited set of of instructions.

**Comment by erikzhang** [comment]
Agree with @shargon

**Comment by vncoelho** [comment]
You edited from @shargon to @lightszero, @erikzhang. hauehauea
Now, effectively, more on the .bin side...aheuahuea

Maybe we can close this PR and open a new one more clear, @lightszero.

**Comment by igormcoelho** [comment]
Liked your view lights, double extension seems nice to me. nvm.bin then? nvm.jsin for the manifest and avi perhaps

**Comment by lock9** [comment]
Hello @neo-project/core, can we solve this conversation? It looks something very easy to be decided.
@vncoelho can you fix the conflicts, please?

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/pull/903

According to the discussion here, we should change the name to `.nef`.

**Comment by vncoelho** [comment]
Moved to https://github.com/neo-project/neo-devpack-dotnet/pull/75

**Pull request closed without merging**
