### PR TITLE
Add ByteString

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by devhawk** [comment]
Can we merge #362 first?

**Comment by erikzhang** [comment]
> Can we merge #362 first?

I will merge it after the alias is reverted.

**Comment by devhawk** [comment]
> I will merge it after the alias is reverted.

If we revert the alias, it won't compile

**Comment by chenzhitong** [comment]
Fixed UT https://github.com/neo-project/neo-devpack-dotnet/pull/377

**Review by Tommo-L — APPROVED** [review]

**Pull request merged**
