### PR TITLE
Update OracleResponseCode codes

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-devpack-dotnet/issues/799

### CODE REVIEW

**Review by Liaojinghui — APPROVED** [review]

**Comment by vncoelho** [comment]
Not sure, but this PR is possible subjected to attack as well in case of future resync.
Perhaps this should be marked.

What is the idea for handling this in the future @shargon @Liaojinghui @superboyiii ?

**Comment by Liaojinghui** [comment]
this is devpack, how will this impack the resync?

**Comment by vncoelho** [comment]
My bad....

**Comment by Liaojinghui** [comment]
> Member

No problem, wont hurt to double check a pr anyway.

**Pull request merged**
