### PR TITLE
break the method convert

### PR DESCRIPTION
**Pull request by Liaojinghui**
This pr changes no logic to the compiler but only break the 5000 line `methodconvert` file into multiple subfiles.

For the ease of maintaing the compiler and possibly add more features to the compiler, we need to break this super huge file to make it clear how neo compile C# into NEF.

Why we need this pr?

1. we need to have a detailed document to tell the developers what part of C# is supported, having that document requires a thourough understanding of the compiler. And making the compile process clear helps us understand the code.

2. Current compiler still misses some of C# features, we need a clear structure to check what is missing.

### CODE REVIEW

**Comment by Liaojinghui** [comment]
@shargon please review

**Comment by shargon** [comment]
We said first bugs then optimization a features xD

**Comment by Liaojinghui** [comment]
> We said first bugs then optimization a features xD

this is for adding tests, comments, documents, and checking bugs. 

Take a look how easy it became to check what test is missing:

Screenshot 2023-11-12 at 8 15 48 PM

**Comment by shargon** [comment]
@Liaojinghui https://github.com/neo-project/neo/issues/2955 Point 2 🙄

Also, we already agree to focus on bugs first.

> There are already tons of name style issues, comments issues, typo issues. Let's focus on fixing bugs please. https://github.com/neo-project/neo-modules/pull/815#discussion_r1390417397

Review this PR require to review all the 58 changed files, it spend a ton of time for ensuring that the logic was not changed, I'm agree that it's better like you did, but small PR are easy to review.

**Comment by Liaojinghui** [comment]
Not changing a single line of code, just split the big files.

**Comment by Liaojinghui** [comment]
I will close this pr to break the changes step by step into smaller prs.

**Pull request closed without merging**
