### PR TITLE
fix notequal with null problem

### LINKED ISSUE #184: Two convert cases will fail
### One case

```csharp
public static bool CheckNullConvertToBigInteger(string code)
{
       var m = Storage.Get(code);
       var k = m?.AsBigInteger();  // <---- this convert will throw ex, but if we remove the `?`, it will not throw
       return k == null;
}
```

Then the compiler will throw the following exceptions 

```
 消息: 
    Initialization method Neo.Compiler.MSIL.UnitTest_NULL.Init threw exception. System.Exception: error:System.Boolean Neo.Compiler.MSIL.TestClasses.Contract_NULL::StorageAndConvertToBigInteger(System.String)::IL_0024 Call System.Boolean System.Nullable`1<System.Numerics.BigInteger>::get_HasValue() ---> System.Exception: unknown call: System.Boolean System.Nullable`1<System.Numerics.BigInteger>::get_HasValue()
       in: System.Boolean Neo.Compiler.MSIL.TestClasses.Contract_NULL::StorageAndConvertToBigInteger(System.String)
    .
  堆栈跟踪: 
    ModuleConverter._ConvertCall(OpCode src, NeoMethod to) 行 742
    ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) 行 888
    ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) 行 434
```
> It's problably we have not handle the `System.Boolean System.Nullable`1<System.Numerics.BigInteger>::get_HasValue()`

But if we rewrite the code as following, it will be compiled successful.

```csharp
public static bool CheckNullConvertToBigInteger(string code)
{
       var m = Storage.Get(code);
       var k = m?.AsBigInteger()??0;  
       return k == null;
}
```

### Another case

```csharp
public static bool CheckStorageIsNotNull(string operation, object[] args)
{
        var m = Storage.Get(code); // if code isn't exist in storage
       return m != null;  // <---- The vm will execute failed, as this code will be parsed to OpCode.GT 
 }
```
image

#### How to solve it?
One way is to add `null` support in vm `Opcode.GT`.

Another is to add a check in compiler, and convert to `OpCode.NOTEQUAL` or `OpCode.ISNULL`, which must recognize the `null` parameters.  

This is closed by #183

### PR DESCRIPTION
**Pull request by lightszero**
fixed #184 
fix a notequal with null problem.

in c#
```c#
a!=null
```

now convert to
```
ISNULL
NOT
```

### CODE REVIEW

**Comment by superboyiii** [comment]
Tested, it works as expected. Test pass.

**Comment by superboyiii** [comment]
@lightszero This PR solves the second issue. There's another issue inclued in https://github.com/neo-project/neo-devpack-dotnet/issues/184
The first case still has the same issue. Will you go on fixing it in this PR?

**Comment by Tommo-L** [comment]
It works fine.  The C # compiler is a bit powerful, `null! = M` and `m! = Null` both put `null` as the last parameter. 😂

**Comment by lightszero** [comment]
> @lightszero This PR solves the second issue. There's another issue inclued in #184
> The first case still has the same issue. Will you go on fixing it in this PR?

we should disscus that in another issue.

**Pull request merged**
