### PR TITLE
Support conditional compilation

### LINKED ISSUE #664: nccs should support #if Debug conditional compilation
nccs can't detect #if Debug statement which neon/Neo.Compiler.MSIL compiler supports.

### PR DESCRIPTION
**Pull request by erikzhang**
Close #664

### CODE REVIEW

**Comment by erikzhang** [comment]
We can call `Runtime.Log()` in a `#if DEBUG` block. It is useful.

**Review by shargon — DISMISSED** [review]
Agree, It could be useful

**Review by devhawk — APPROVED** [review]
The basic *idea* of conditional compilation support gets a big 👍 from me.

I'm not a fan of *how* we've implemented this in `nccs`. It feels to me that `nccs` is replicating a bunch of MSBuild logic - including conditional compilation settings - that would be better left to MSBuild. But that's a general issue w/ how `nccs` interacts with project files that is not specific to this PR

**Comment by roschler** [comment]
I want to emphasize the need for `Runtime.Log()` statements as was pointed out.

This leads to a real workflow problem because you can't use those in a method marked as `[Safe]`.  You will get a SYSCALL error from the VM.  So you end up with this inconvenient workflow.  You have to remove the `[Safe]` attribute from every method that uses `Runtime.Log()` calls during dev, and then (have to remember) to restore that attribute and also comment out all the `Runtime.Log()` calls when it comes time to publish your smart contract.  What happens if you forget to restore the attribute?

Why doesn't the NVM just ignore those calls in a `[Safe]` method instead of throwing an error?

**Comment by erikzhang** [comment]
> This leads to a real workflow problem because you can't use those in a method marked as [Safe].

With this pr, you can use `#if DEBUG` to disable `[Safe]` temporarily now.

**Comment by roschler** [comment]
Thanks Erik!  How do I get this version into my build set?

**Comment by erikzhang** [comment]
After our 3.2.2 release, you can get compiler, framework, and project template from nuget.

**Pull request merged**
