### PR TITLE
Safe Attribute

### PR DESCRIPTION
**Pull request by shargon**
Require https://github.com/neo-project/neo/pull/2120 for UT pass
Wait for https://github.com/neo-project/neo-devpack-dotnet/pull/391

### CODE REVIEW

**Comment by shargon** [comment]
After merge #391 I think that we can merge this one and fix the UT in https://github.com/neo-project/neo-devpack-dotnet/pull/402 (update nuget) , What do you think?

**Comment by superboyiii** [comment]
I test it merged with https://github.com/neo-project/neo-devpack-dotnet/pull/391 and https://github.com/neo-project/neo-devpack-dotnet/pull/402, it works well.
image
By the way, maybe we should make some method forced to be unsafe when generated such like which including storage write(mint, deploy...)

**Comment by shargon** [comment]
@superboyiii safe should be used wisely :)

**Comment by superboyiii** [comment]
> @superboyiii safe should be used wisely :)

For me it's OK for Preview4.

**Comment by shargon** [comment]
Will be merged with #402 https://github.com/chenzhitong/neo-devpack-dotnet/pull/6

**Comment by shargon** [comment]
Closed because it will come with https://github.com/neo-project/neo-devpack-dotnet/pull/402

**Pull request closed without merging**
