### PR TITLE
test large overflows and underflows for EnsureIntegerInRange

### PR DESCRIPTION
**Pull request by Hecate2**
The correctness of OpCode.AND depends on the representation of BigInteger in bytes, and I am really suspicious whether AND is correct. Here are some examples of bytes representations.
https://learn.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.tobytearray?view=net-8.0
MOD is safe, no matter how BigInteger is implemented in bytes.

### CODE REVIEW

**Review by shargon — DISMISSED** [review]

**Comment by Jim8y** [comment]
Need unit test to demonstrate the problem.

**Comment by Hecate2** [comment]
> Need unit test to demonstrate the problem. 

I have not come up with any test case to demonstrate that AND is wrong, but I will try it in 24 hrs

**Comment by vncoelho** [comment]
For BigIntenger Negative values it may be the error if I understood correctly

**Review by shargon — COMMENTED** [review]
We should ensure that is well covered with the current UT

**Comment by Hecate2** [comment]
In tests I found that AND works well, while MOD is wrong. In C#, (-1 mod 5) returns -1. In other languages the result is often 4 😰

**Comment by nan01ab** [comment]
> In tests I found that AND works well, while MOD is wrong. In C#, (-1 mod 5) returns -1. In other languages the result is often 4 😰

Other languages are Python?  C, Java, Rust etc. have the same semantics as C#.

**Comment by Jim8y** [comment]
@Hecate2 test should cover signed and unsigned.

**Comment by Hecate2** [comment]
> @Hecate2 test should cover signed and unsigned. 

ok

**Review by shargon — APPROVED** [review]

**Pull request merged**
