### PR TITLE
implement ISNULL

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-vm/issues/215

### CODE REVIEW

**Comment by shargon** [comment]
> made some fix.
"==null"
always had 2 codes in IL
LDNULL
CEQ

But it works as `==null` too?

**Comment by lightszero** [comment]
> > made some fix.
> > "==null"
> > always had 2 codes in IL
> > LDNULL
> > CEQ
> 
> But it works as `==null` too?
```
a==null
a is null
null==a
```
all workd

**Comment by shargon** [comment]
It works perfect @lightszero

**Comment by shargon** [comment]
@lightszero could you approve it?

**Pull request merged**
