### PR TITLE
Update nugets

### PR DESCRIPTION
**Pull request by shargon**
There are projects with different version of dotnet or .net standard

### CODE REVIEW

**Comment by erikzhang** [comment]
I think it's meaningless.

**Comment by shargon** [comment]
I think that all projects should share the same version of the framework

**Comment by erikzhang** [comment]
As a library, the lower the version of the framework, the better.

**Comment by shargon** [comment]
Then, we need to review if any security issue was fixed in any of this upgrades

**Comment by erikzhang** [comment]
> Then, we need to review if any security issue was fixed in any of this upgrades

No need to review. The framework version is not the runtime version.

**Comment by shargon** [comment]
Let's just change it for only update the nugets

**Comment by erikzhang** [comment]
I can't see the benefits of upgrading the dependencies of unit tests.

**Comment by shargon** [comment]
I ussally have the obsession of have the last packages 😂

**Comment by erikzhang** [comment]
Let's upgrade the dependencies only when necessary. Because old dependencies work very well, upgrades can have unpredictable compatibility issues. (although this probability is very low)

**Pull request closed without merging**
