### PR TITLE
Fix paths

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-devpack-dotnet/issues/721

### CODE REVIEW

**Review by Liaojinghui — APPROVED** [review]

**Comment by devhawk** [comment]
We should add a test that actually runs the tool from the command line so we don't get a bug like this again

**Review by erikzhang — APPROVED** [review]

**Comment by erikzhang** [comment]
Tested?

**Comment by Liaojinghui** [comment]
Problem gone on my machine

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shargon** [comment]
I tested it locally, @superboyiii could you confirm that the issue was fixed?

**Comment by Liaojinghui** [comment]
All tests pass on my machine as well

**Pull request merged**
