### PR TITLE
Apply #142 changes (3x)

### PR DESCRIPTION
**Pull request by shargon**
Apply fixes of https://github.com/neo-project/neo-devpack-dotnet/pull/142 in 3x

### CODE REVIEW

**Comment by superboyiii** [comment]
I made some tests, issues exist here:
```
D:\Shargon-devpack-175\Nep5sc\Nep5sc>neon Nep5sc.csproj
Neo.Compiler.MSIL console app v3.0.0.0
Compiling from csproj project
Unhandled exception. System.ArgumentException: (14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
   at Neo.Compiler.Compiler.Assembly.Create(Compilation comp) in D:\Shargon-devpack-175\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Compiler.cs:line 48
   at Neo.Compiler.Compiler.CompileCSFile(String[] filenames, String[] references, Boolean releaseMode) in D:\Shargon-devpack-175\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Compiler.cs:line 175
   at Neo.Compiler.Compiler.CompileCSProj(String filename, Boolean releaseMode) in D:\Shargon-devpack-175\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Compiler.cs:line 77
   at Neo.Compiler.Program.Main(String[] args) in D:\Shargon-devpack-175\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 76
```
And I find `Neo.SmartContract.Framework.dll` need to be copied to SC project root file manually for ```neon xxx.csoj```. Shall it be done automatically?

**Comment by shargon** [comment]
Could you zip your project and send it to me?

**Comment by shargon** [comment]
> And I find Neo.SmartContract.Framework.dll need to be copied to SC project root file manually for neon xxx.csoj. Shall it be done automatically?

Yes should be done automatically

**Comment by superboyiii** [comment]
@shargon  Here.
https://drive.google.com/file/d/1H4auYQarHkubi7n65IgHMmvxAtwyWsPv/view?usp=sharing

**Comment by shargon** [comment]
image
 
The problem is that you have already `obj` folder, so it's hard to detect what is source and what it's not ... I will try to exclude the bin and obj folder

**Comment by superboyiii** [comment]
@shargon Works well now.
image
image

**Pull request merged**
