### PR TITLE
Fix return type of bool

### PR DESCRIPTION
**Pull request by ShawnYun**
Add a Convert to ensure that the return type is Boolean.
According to https://github.com/neo-project/neo/issues/1912

### CODE REVIEW

**Comment by erikzhang** [comment]
I think it's not necessary. The VM can automatically convert it to `Boolean`.

**Comment by ShawnYun** [comment]
But according to neo-project/neo#1912.
Smart contract return type is irregular when return Boolean result, sometimes it's 1, sometimes it's true.

**Comment by erikzhang** [comment]
> sometimes it's 1, sometimes it's true.

This will not cause any impact.

**Comment by shargon** [comment]
If is not a return the 'error' still here, what it's the IL code generated?

**Comment by ShawnYun** [comment]
Yes, maybe it is confusing.

**Comment by erikzhang** [comment]
> what it's the IL code generated?

There is no `bool` type in IL. I don't think it is an issue.

**Comment by csmuller** [comment]
> > sometimes it's 1, sometimes it's true.
> 
> This will not cause any impact.

If a dApp developer relies on the contract manifest which states that a `Boolean` is returned but gets an `Integer`, that does have an impact. I don't care if booleans are returned as `Boolean` (true, false) or `Integer` (0, 1), what's important is that it must be consistent with what the manifest says.

**Comment by gsmachado** [comment]
> I don't care if booleans are returned as `Boolean` (true, false) or `Integer` (0, 1), what's important is that it must be consistent with what the manifest says.

I completely agree with this. 💯 

If we want to make Neo a developer-friendly platform, I think this argument is pretty reasonable.

**Pull request closed without merging**
