### PR TITLE
Reduce notifications

### PR DESCRIPTION
**Pull request by shargon**
Reduce notifications during compilation

### CODE REVIEW

**Comment by Jim8y** [comment]
Why? I still could not understand recent prs, do they solve real problems at all? more like minor code optimization. If you do this, we can push many many similar prs every day.

**Review by Jim8y — APPROVED** [review]

**Comment by Jim8y** [comment]
Up to you to decide if you realy want to do prs like this. I wont block it.

**Comment by shargon** [comment]
> Why? I still could not understand recent prs, do they solve real problems at all? more like minor code optimization. If you do this, we can push many many similar prs every day.

This is the review for the previous one

**Comment by cschuchardt88** [comment]
> Up to you to decide if you realy want to do prs like this. I wont block it.

I will.

You need to revert it. Before that; copy to other branch and make changes and than put in new PR to merge that branch after the fixes and code is right.

**Pull request merged**
