### PR TITLE
Sort methods during compilation

### PR DESCRIPTION
**Pull request by shargon**
- Sorted Abi methods by name/offsets.

### CODE REVIEW

**Comment by shargon** [comment]
@erikzhang I think that this can be merged, even if another is the solution to the problem, it will be faster to obtain the standard methods if they are at the beginning of the method array.

**Comment by erikzhang** [comment]
This PR can solve the current problem. But it can only fix one method, and I am worried that there will be other special methods that need to be fixed in the future. So I don't think it should be merged, we should focus on #1973.

**Comment by shargon** [comment]
Agree, but more than a fix it's about have some rules in Abi generation, sort by `offset` at least

**Comment by shargon** [comment]
@erikzhang Please don't think that it's a fix for https://github.com/neo-project/neo/pull/1964 , now it's only a deterministic way to sort the methods during compilation.

**Comment by erikzhang** [comment]
Tested?

**Comment by shargon** [comment]
@superboyiii could you test it?

**Comment by shargon** [comment]
Ping @superboyiii

**Comment by superboyiii** [comment]
> Ping @superboyiii

Sorry for late, I'll test it tommorrow.

**Comment by superboyiii** [comment]
@shargon @erikzhang It works well on mine. Method names and offsets are all sorted in asc.
```
{
    "methods":[
        {
            "name":"_initialize",
            "offset":"0",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Void"
        },
        {
            "name":"balanceOf",
            "offset":"95",
            "safe":false,
            "parameters":[
                {
                    "name":"account",
                    "type":"Hash160"
                }
            ],
            "returntype":"Integer"
        },
        {
            "name":"decimals",
            "offset":"202",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Integer"
        },
        {
            "name":"deploy",
            "offset":"224",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Boolean"
        },
        {
            "name":"destroy",
            "offset":"411",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Void"
        },
        {
            "name":"disablePayment",
            "offset":"510",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Void"
        },
        {
            "name":"enablePayment",
            "offset":"584",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Void"
        },
        {
            "name":"onPayment",
            "offset":"1092",
            "safe":false,
            "parameters":[
                {
                    "name":"from",
                    "type":"Hash160"
                },
                {
                    "name":"amount",
                    "type":"Integer"
                },
                {
                    "name":"data",
                    "type":"Any"
                }
            ],
            "returntype":"Void"
        },
        {
            "name":"symbol",
            "offset":"1475",
            "safe":false,
            "parameters":[

            ],
            "returntype":"String"
        },
        {
            "name":"totalSupply",
            "offset":"1481",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Integer"
        },
        {
            "name":"transfer",
            "offset":"1487",
            "safe":false,
            "parameters":[
                {
                    "name":"from",
                    "type":"Hash160"
                },
                {
                    "name":"to",
                    "type":"Hash160"
                },
                {
                    "name":"amount",
                    "type":"Integer"
                },
                {
                    "name":"data",
                    "type":"Any"
                }
            ],
            "returntype":"Boolean"
        },
        {
            "name":"update",
            "offset":"1809",
            "safe":false,
            "parameters":[
                {
                    "name":"nefFile",
                    "type":"ByteArray"
                },
                {
                    "name":"manifest",
                    "type":"String"
                }
            ],
            "returntype":"Void"
        },
        {
            "name":"verify",
            "offset":"1909",
            "safe":false,
            "parameters":[

            ],
            "returntype":"Boolean"
        }
    ],
    "events":[
        {
            "name":"Transfer",
            "parameters":[
                {
                    "name":"arg1",
                    "type":"Hash160"
                },
                {
                    "name":"arg2",
                    "type":"Hash160"
                },
                {
                    "name":"arg3",
                    "type":"Integer"
                }
            ]
        }
    ]
}
```

**Comment by superboyiii** [comment]
> @shargon @erikzhang It works well on mine. Method names and offsets are all sorted in asc. I think it's a good rule for abi generation.
> 
> ```
> {
>     "methods":[
>         {
>             "name":"_initialize",
>             "offset":"0",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Void"
>         },
>         {
>             "name":"balanceOf",
>             "offset":"95",
>             "safe":false,
>             "parameters":[
>                 {
>                     "name":"account",
>                     "type":"Hash160"
>                 }
>             ],
>             "returntype":"Integer"
>         },
>         {
>             "name":"decimals",
>             "offset":"202",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Integer"
>         },
>         {
>             "name":"deploy",
>             "offset":"224",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Boolean"
>         },
>         {
>             "name":"destroy",
>             "offset":"411",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Void"
>         },
>         {
>             "name":"disablePayment",
>             "offset":"510",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Void"
>         },
>         {
>             "name":"enablePayment",
>             "offset":"584",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Void"
>         },
>         {
>             "name":"onPayment",
>             "offset":"1092",
>             "safe":false,
>             "parameters":[
>                 {
>                     "name":"from",
>                     "type":"Hash160"
>                 },
>                 {
>                     "name":"amount",
>                     "type":"Integer"
>                 },
>                 {
>                     "name":"data",
>                     "type":"Any"
>                 }
>             ],
>             "returntype":"Void"
>         },
>         {
>             "name":"symbol",
>             "offset":"1475",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"String"
>         },
>         {
>             "name":"totalSupply",
>             "offset":"1481",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Integer"
>         },
>         {
>             "name":"transfer",
>             "offset":"1487",
>             "safe":false,
>             "parameters":[
>                 {
>                     "name":"from",
>                     "type":"Hash160"
>                 },
>                 {
>                     "name":"to",
>                     "type":"Hash160"
>                 },
>                 {
>                     "name":"amount",
>                     "type":"Integer"
>                 },
>                 {
>                     "name":"data",
>                     "type":"Any"
>                 }
>             ],
>             "returntype":"Boolean"
>         },
>         {
>             "name":"update",
>             "offset":"1809",
>             "safe":false,
>             "parameters":[
>                 {
>                     "name":"nefFile",
>                     "type":"ByteArray"
>                 },
>                 {
>                     "name":"manifest",
>                     "type":"String"
>                 }
>             ],
>             "returntype":"Void"
>         },
>         {
>             "name":"verify",
>             "offset":"1909",
>             "safe":false,
>             "parameters":[
> 
>             ],
>             "returntype":"Boolean"
>         }
>     ],
>     "events":[
>         {
>             "name":"Transfer",
>             "parameters":[
>                 {
>                     "name":"arg1",
>                     "type":"Hash160"
>                 },
>                 {
>                     "name":"arg2",
>                     "type":"Hash160"
>                 },
>                 {
>                     "name":"arg3",
>                     "type":"Integer"
>                 }
>             ]
>         }
>     ]
> }
> ```

**Comment by shargon** [comment]
Merge?

**Comment by superboyiii** [comment]
@erikzhang Merge?

**Review by superboyiii — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
