### PR TITLE
Sync native rename

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-devpack-dotnet/issues/407
Sync with https://github.com/neo-project/neo/pull/2152

### CODE REVIEW

**Comment by shargon** [comment]
Merge?

**Comment by superboyiii** [comment]
> Merge?

Wait for neon Preview4 been released, then it could be merged.

**Comment by shargon** [comment]
Wait for https://github.com/neo-project/neo-devpack-dotnet/pull/396

**Comment by shargon** [comment]
Merge?

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
