### PR TITLE
Branch autogen entrypoint

### PR DESCRIPTION
**Pull request by lightszero**
if you do not write a Main function in smart contract.
now we can add one automatic:

```
    class Contract_autoentrypoint : SmartContract.Framework.SmartContract
    {
        //there is no main here, it can be auto generation.
        //object Main(string name,object[])
        //{
        //    if(name=="call01")
        //    {
        //        return call01();
        //    }
        //    if(name=="call02")
        //    {
        //        call02(_params[0],params[1]);
        //        return 0; //null or "" or 0 or false , if call02 is void,will add return 0;
        //    }
        //    throw //if no method was found,make vm fault.
        //}
        public static byte[] call01()
        {
            var nb = new byte[] { 1, 2, 3, 4 };
            return nb;
        }
        public static void call02(string a,int b)
        {
            Neo.SmartContract.Framework.Services.Neo.Runtime.Log(a);
        }
    }
```

### CODE REVIEW

**Comment by shargon** [comment]
wait please

**Comment by shargon** [comment]
Very nice work @lightszero ! i love it! my only concern is about verification, how we can deal with this, i think that it should return false in verification.

**Comment by shargon** [comment]
What about...

```csharp
public static bool onVerification()
{
  // Logic here?
  return false;
}
```

**Comment by lightszero** [comment]
> This idea is really good. Congratulation Lights.
> 
> I reviewed most of this PR in the other PR... but I didn't like that one 😂 hahaha we need testing in both ways: standard and non-standard entrypoints.

this idea is from eric.

**Comment by lightszero** [comment]
> Very nice work @lightszero ! i love it! my only concern is about verification, how we can deal with this, i think that it should return false in verification.

err...,that is a question.

as eric said all neo3 contract is Main(string,object[])

but how about verification?
@erikzhang

**Comment by igormcoelho** [comment]
Congratulations for the idea @erikzhang :joy:

if all is unified, fine.

**Comment by lightszero** [comment]
> Congratulations for the idea @erikzhang 😂
> 
> if all is unified, fine.
> 
> I think your case is not a problem Shargon, because the method would push0 , and conversion already knows its a bool type, and ot would be returned normally. The only "edge" case is a void metgod, which is being treated as "return false", right lights?
> 
> This one is just when you dont declare your main, so it creates for you. The other PR is more problematic.
object Main(string methodname,object[] params）
{
    if(methodname=="xxx")
    {
        xxx();//if is a void xxx(), will add a return 0 too;
       return 0;
    }
}

**Comment by lightszero** [comment]
I think we can merge this first.
and discuss about verification more.

**Comment by shargon** [comment]
I was thinking exactly in this, an attribute!

**Comment by erikzhang** [comment]
For verification, you can write the `Main()` function manually.

**Comment by erikzhang** [comment]
We should also update the templates.

**Comment by shargon** [comment]
> For verification, you can write the Main() function manually.

But by default, should `return false`

**Comment by igormcoelho** [comment]
I think that unused functions should FAULT on Application.

**Comment by lightszero** [comment]
already fault，but fault is not have param in neovm. we can not set a fault reason.

**Comment by igormcoelho** [comment]
I think that FAULT reason is more important for a better Exception handling... in the future.

**Comment by lightszero** [comment]
maybe add a notify before throw.

**Comment by igormcoelho** [comment]
Just to clarify, the problem is the THROW itself... sometimes you want to invoke something, and if it fails, you proceed with other alternative. So, we actually need exception handling. I'm just mentioning here because it would be useful together with this feature here... but perhaps it's time to start thinking on strategies to allow exception handling on vm.

**Pull request merged**
