### PR TITLE
TestingEngine: Native contracts manifest reuse

### PR DESCRIPTION
**Pull request by shargon**
Wait for https://github.com/neo-project/neo/pull/3171

- Added TestingEngine tests to workflow.
- Reused manifest from neo core.
- Renamed Native contracts to be the same as core.

### CODE REVIEW

**Comment by Jim8y** [comment]
I have a problem, every time i run, changes like this happen. Please fix.

image

**Comment by Jim8y** [comment]
Its in testingArtifacts/Contract_Contract.cs and other two. Also in template/neocontractxxx/testingArtigfactxxxx

**Comment by shargon** [comment]
> I have a problem, every time i run, changes like this happen. Please fix.
> 
> image

Looks like your build It's not deterministic ..

**Comment by shargon** [comment]
@Jim8y could you check if it's your compiler version inside the neffile?

**Comment by Jim8y** [comment]
> @Jim8y could you check if it's your compiler version inside the neffile?

Why it's related to compiler version? Isn't it's built from the source code?

**Comment by shargon** [comment]
> > @Jim8y could you check if it's your compiler version inside the neffile?
> 
> Why it's related to compiler version? Isn't it's built from the source code?

Because it's inside the `nefFile`

**Comment by shargon** [comment]
@neo-project/core http://seed2t5.neo.org:20332 `TotalSupply` it's not 100m?

**Comment by shargon** [comment]
@Jim8y the conflicts are fixed

**Review by Jim8y — APPROVED** [review]

**Pull request merged**
